export const SET_WEATHER_ITEM = 'SET_WEATHER_ITEM';
export const SET_LIGHT_SCENE = 'SET_LIGHT_SCENE';
export const SET_CURRENT_WEATHER = 'SET_CURRENT_WEATHER';
export const SET_FORECAST = 'SET_FORECAST';